# Use the spark:python3 image as the base image
FROM spark:python3

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app
